title: Chris Blocher | Content Designer & Mentor
description: I specialize in creating clear, engaging, and user-centric content experiences. With a passion for accessible design and strategic storytelling.
show_downloads: false 
linkedin: "https://www.linkedin.com/in/chrisblocher"