title: This is the title of the site
description: This is the description of the site
show_downloads: "false"
linkedin: "https://www.linkedin.com/in/chrisblocher"
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
