title: Chris Blocher | Technical Writer & Mentor
description: I specialize in creating clear, engaging, and user-centric content experiences. With a passion for accessible design and strategic storytelling.
show_downloads: false 
theme: jekyll-theme-primer
linkedin: "https://www.linkedin.com/in/chrisblocher"
